### ISSUE TITLE
Enter Password

### ISSUE THREAD

**Issue by niekheezemans** [EddyVerbruggen/cordova-plugin-touch-id#1]
Hi Eddy,

Great Plugin! Was wandering if you plan to also support to enter the password from the Touch ID screen? Or maybe also that it will be possible to disable the "Enter password" function.

Thanks in advance!

**Comment by EddyVerbruggen** [comment]
Hi, found a solution. Available in 2.0.0.

Cheers,
Eddy

**Comment by immigrationanytime** [comment]
Hi Eddy,
I added the plugin. The first screen I get does not show the "Enter Passcode" button. If my fingerprint does not match then a second screen opens with the "Enter Passcode" option.  Am I doing something wrong?
Thanks,
Hans

**Comment by EddyVerbruggen** [comment]
Hi Hans, that may be the default these days - what do other Touch ID enabled apps show as the first screen (make sure the attempt before was OK).

**Comment by immigrationanytime** [comment]
thanks. I will check that. Do you have a list of error messages and error codes returned by the plugin?

**Comment by EddyVerbruggen** [comment]
Yeah, in the error callback you'll get the objective-c errorcode and localized description of [this list of errors](https://developer.apple.com/library/ios/documentation/LocalAuthentication/Reference/LAContext_Class/#//apple_ref/c/tdef/LAError)

**Comment by immigrationanytime** [comment]
I verified that user is first asked to touch, then if that fails, either "Enter Passcode" or "Enter Password" option appears.
Thanks for the error codes.
