### ISSUE TITLE
Please share UI template and Script?

### ISSUE THREAD

**Issue by ankushgoyal27** [EddyVerbruggen/cordova-plugin-touch-id#10]
Hi Eddy,

Its a very nice tutorial. If possible, please share the HTML templates and script file.

Thanks.

Ankush

**Comment by EddyVerbruggen** [comment]
What exactly are you referring to?

**Comment by ankushgoyal27** [comment]
I am looking for a working example for the cordova-plugin-touch-id. You have upload the screenshot, I am looking for the implementation.

**Comment by EddyVerbruggen** [comment]
Just start a new app with the Cordova CLI, wait for `deviceready` to fire, and call a function as shown [in the readme](https://github.com/EddyVerbruggen/cordova-plugin-touch-id#5-security).

Alternatively, clone the demo app by clicking the big orange/red button at the top [here](http://plugins.telerik.com/cordova/plugin/touch-id).
