### ISSUE TITLE
Getting build error in TouchID.m file

### ISSUE THREAD

**Issue by ankushgoyal27** [EddyVerbruggen/cordova-plugin-touch-id#11]
/Users/devmobile/Desktop/TouchID/workshop/platforms/ios/Workshop/Plugins/cordova-plugin-touch-id/TouchID.m:49:41: warning: 
      undeclared selector 'evaluatedPolicyDomainState' [-Wundeclared-selector]
    if (![laContext respondsToSelector:@selector(evaluatedPolicyDomainState)]) {
                                        ^
/Users/devmobile/Desktop/TouchID/workshop/platforms/ios/Workshop/Plugins/cordova-plugin-touch-id/TouchID.m:54:33: error: 
      no visible @interface for 'LAContext' declares the selector
      'evaluatedPolicyDomainState'
    NSData * state = [laContext evaluatedPolicyDomainState];
                      ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.

** BUILD FAILED **


The following build commands failed:
	CompileC build/Workshop.build/Debug-iphonesimulator/Workshop.build/Objects-normal/i386/TouchID.o Workshop/Plugins/cordova-plugin-touch-id/TouchID.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/devmobile/Desktop/TouchID/workshop/platforms/ios/cordova/build-debug.xcconfig,-project,Workshop.xcodeproj,ARCHS=i386,-target,Workshop,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/devmobile/Desktop/TouchID/workshop/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/devmobile/Desktop/TouchID/workshop/platforms/ios/build/sharedpch

**Comment by EddyVerbruggen** [comment]
Looks like iOS7 SDK. Can you please use XCode 6 with a recent SDK and try again?

**Comment by ankushgoyal27** [comment]
I Havd iOS 8.4 SDK

xcodebuild -showsdks
OS X SDKs:
	OS X 10.9                     	-sdk macosx10.9
	OS X 10.10                    	-sdk macosx10.10

iOS SDKs:
	iOS 8.4                       	-sdk iphoneos8.4

iOS Simulator SDKs:
	Simulator - iOS 8.4           	-sdk iphonesimulator8.4

**Comment by EddyVerbruggen** [comment]
Please try iOS 9.x SDK

**Comment by ankushgoyal27** [comment]
It is working now. Thanks

**Comment by vishvendu** [comment]
I'm Having the same problem how did you find the solution ? @ankushgoyal27

**Comment by ankushgoyal27** [comment]
Hello, update the Mac OS and XCode with the latest version, this will resolve your issue. 

Thanks,

Ankush
