### ISSUE TITLE
Build Failed when adding this plugin

### ISSUE THREAD

**Issue by vishvendu** [EddyVerbruggen/cordova-plugin-touch-id#12]
/Plugins/cordova-plugin-touch-id/TouchID.m:54:33:
error: no visible @interface for 'LAContext' declares the selector 'evaluatedPolicyDomainState' NSData \* state = [laContext evaluatedPolicyDomainState];
1 warning and 1 error generated.

**Comment by EddyVerbruggen** [comment]
Which iOS SDK are you building with?
