### ISSUE TITLE
Not work in app.run method 

### ISSUE THREAD

**Issue by chetanbuddh** [EddyVerbruggen/cordova-plugin-touch-id#14]
This is my app.run code.
when this run it display white screen in my iphone 
`app.run(function($ionicPlatform, $rootScope, $http,$window) {
  
 $window.plugins.touchid.isAvailable(function() {
        alert('available!');
       // success handler: TouchID available
    },
    function(msg) {
        alert('not available, message: ' + msg);
        // error handler: no TouchID available
    }); 
});`

i install plugin using npm

**Comment by EddyVerbruggen** [comment]
This results in a white screen, when doing what? Sounds like a JS error to me.. try adding a window.onerror handler.

**Comment by chetanbuddh** [comment]
app.run(function($ionicPlatform) {
 
 setTimeout(function(){
      window.plugins.touchid.isAvailable(
        function()
        {
            alert('available!');// success handler: TouchID available
                window.plugins.touchid.verifyFingerprint(
               'Scan your fingerprint please',
                function(msg)
                {
                    alert('ok: ' + JSON.stringify(msg));
                },
                function(msg) {
                    alert('not ok: ' + JSON.stringify(msg));
                });
        },
        function(msg)
        {
            alert('not available, message: ' + JSON.stringify(msg));// error handler: no TouchID available
        }
    );
  },1000);
});

**Comment by EddyVerbruggen** [comment]
Also known as `deviceready`? :)
