### ISSUE TITLE
Plugin does not load on mobile device ios

### ISSUE THREAD

**Issue by ibondoc22** [EddyVerbruggen/cordova-plugin-touch-id#16]
when installing the plugin using npm or github

```
$ cordova plugin add cordova-plugin-touch-id`
$ cordova prepare
```

or

```
$ cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-touch-id
$ cordova prepare
```

using cordova browser the plugin seems to work, but for mobile device (iPhone 6, iOs 9) the plugin does not seem to load at all.

Thanks,

**Comment by EddyVerbruggen** [comment]
So what have you tried to fix it, and how exactly are you testing it?

**Comment by ibondoc22** [comment]
Hi Eddy,

tried adding this in my index.html

```
<button onclick="window.plugins.touchid.isAvailable(function(msg) {alert('ok: ' + msg)}, function(msg) {alert('not ok: ' + msg)})">Touch ID available?</button>
<button onclick="window.plugins.touchid.verifyFingerprint('Scan your fingerprint please', function(msg) {alert('ok: ' + msg)}, function(msg) {alert('not ok: ' + JSON.stringify(msg))})">Scan fingerprint</button>
````

also tried

```
window.plugins.touchid.isAvailable(
  function() {alert('available!')}, // success handler: TouchID available
  function(msg) {alert('not available, message: ' + msg)} // error handler: no TouchID available
);
````

on browser both examples are loading and throwing the error no touchid available, but when testing it with iPhone 6 / iOs9 no feedback at all.

**Comment by EddyVerbruggen** [comment]
That first button should work fine indeed. You are including `cordova.js` and run as a standalone app (not a companion app)?

**Comment by ibondoc22** [comment]
i am currently trying to make it work using the Phonegap development app, but also tried it after building it in build.phonegap.com

cordova.js is included on my index.html

**Comment by EddyVerbruggen** [comment]
The developer app won't work as it doesn't ship with the Touch ID plugin AFAIK.

PhoneGap Build should work, but you must include the plugin in `config.xml`..

**Comment by ibondoc22** [comment]
Thanks Eddy,

I will try this and let you know the outcome.

Thanks,
