### ISSUE TITLE
Returns null on success

### ISSUE THREAD

**Issue by bhavinsetubridge** [EddyVerbruggen/cordova-plugin-touch-id#17]
Hello ..
When i used this plugin for touch id in phonegap.. touch id dialog prompt  successfully ..
it also shows fail message but not showing success message..?

window.plugins.touchid.isAvailable(
                        function(msg) {
                            window.plugins.touchid.verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel(
                        'Scan your fingerprint please', // this will be shown in the native scanner popup
                        'Enter PIN', // this will become the 'Enter password' button label
                            function(msg) {
                                                                                                                    console.log("console "+msg);
                                $("#touchresponse").html(msg);
                                                                                                                    alert(typeof msg);

```
                                                                                                                }, // success handler: fingerprint accepted
                        function(msg) { 
                        $("#touchresponse").html(JSON.stringify(msg));
                        } // error handler with errorcode and localised reason
                        );
                        },    // success handler: TouchID available
                    function(msg) {
                     $("#touchresponse").html(JSON.stringify(msg));
                    } // error handler: no TouchID available
                                                   );
```

**Comment by ElBullet** [comment]
Same problem in Ionic 2

Cordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.3-201611282011
Ionic CLI Version: 2.1.13
Ionic App Lib Version: 2.1.7
Ionic App Scripts Version: 0.0.46
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.7.0
Xcode version: Not installed

```
TouchID.isAvailable()
.then(
    res => {
        console.log('touchid avaiable');
        TouchID.verifyFingerprint('Please scan your fingerprint')
        .then(
            res => {
                console.log('ok: ' + res);
            },
            err => {        
                console.log('error: ' + err);
            }
        );
    },
    err => console.log('touchid not avaiable')
 );
```

Output:
touchid avaiable
ok: null

**Comment by EddyVerbruggen** [comment]
There's no problem. Per the doc the success handler is invoked when OK, the error handler if not:

```js
window.plugins.touchid.verifyFingerprint(
  'Scan your fingerprint please', // this will be shown in the native scanner popup
   function(msg) {alert('ok: ' + msg)}, // success handler: fingerprint accepted
   function(msg) {alert('not ok: ' + JSON.stringify(msg))} // error handler with errorcode and localised reason
);
```

Whatever is or is not passed as an argument to the success handler is irrelevant.
