### ISSUE TITLE
Need to customise the error handler popup which occurs on wrong finger scan 

### ISSUE THREAD

**Issue by hybridapp20161** [EddyVerbruggen/cordova-plugin-touch-id#19]
Hi, 
I am using touch-id plugin #3.2.0, Xcode #8.1 and iOS #10.11.6 . I need to customise the error handler popup which appears when customer using  invalid finger print scan which is not saved in the device. Instead of 'Enter Passcode' and 'Cancel' option, can we use other ways to handle the authentication process like password or OTP and if so please explain how ?
Please help.

**Comment by hybridapp20161** [comment]
Need an alternate option other then device passcode to authenticate the customers.

**Comment by EddyVerbruggen** [comment]
Did you try the both `verifyFingerprint` and `verifyFingerprintWithCustomPasswordFallback` already?
