### ISSUE TITLE
Window.Plugins.touchid is undefined

### ISSUE THREAD

**Issue by jai924** [EddyVerbruggen/cordova-plugin-touch-id#20]
Hi,

I followed the document for manual process to add touch id, But in the console its throwing
Window.plugins.touchid is undefined...can anyone tell why the error is?

**Comment by EddyVerbruggen** [comment]
Why use the manual approach? And you may want to share your project if you want a non-guessy answer.

**Comment by jai924** [comment]
Hi Eddy,

I didn't attached the whole project. Required files are there in the below link. And in config.xml the Touchid path is defined at last.

[](https://www.dropbox.com/s/mo5z6psucgqxtfk/Required%20files.zip?dl=0)

**Comment by EddyVerbruggen** [comment]
`config.xml` contains the declaration for the TouchID feature twice, but that shouldn't mean it doesn't work. Do you wait for `deviceready` to fire before using it?

**Comment by jai924** [comment]
i m sorry for that. I tried with ondeviceready, its not firing the plugin getting the same error

**Comment by EddyVerbruggen** [comment]
OK, I'll stop guessing and close this issue. If you can share the entire project I may take a look but I don't usually support manually added plugins.
