### ISSUE TITLE
enter passcode page

### ISSUE THREAD

**Issue by harshvardhan12** [EddyVerbruggen/cordova-plugin-touch-id#22]
by using this method "window.plugins.touchid.verifyFingerprintWithCustomPasswordFallback" , i am not getting the default enter passcode page after clicking on "Enter Password" button (i am not getting any default screen), whereas by using the method "window.plugins.touchid.verifyFingerprint" i will get the default passcode page, can you please suggest why this is happening.

**Comment by EddyVerbruggen** [comment]
Because that's what's meant by 'With Custom Password Fallback'?

**Comment by harshvardhan12** [comment]
so, while clicking on enter password button where i will type my password if no screen is there.
i am getting error code as -3 if i press on enter password,  the expected scenario is while typing the correct password only he will be able to enter inside the app. what should i do?

**Comment by EddyVerbruggen** [comment]
Add a custom password screen yourself.
