### ISSUE TITLE
Securely store/retrieve data using fingerprint

### ISSUE THREAD

**Issue by ntdaley** [EddyVerbruggen/cordova-plugin-touch-id#24]
Correct me if I'm wrong, but it looks like this library only gives a yes/no on whether the fingerprint matched.  It does not allow me to securely protect data using the fingerprint.  (As can be done with the underlying native library.)
Looking at the .m file, it looks like you're storing dummy data, and not exposing it.

I would like to use the user's fingerprint to secure credentials used to authenticate with my server.
If all I have is a yes/no on whether the fingerprint matched, then I can't really secure anything with it.

**Comment by jamesdixon** [comment]
There's another plugin here that incorporates the cordova keychain module to allow for what you're describiing: https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id

**Comment by EddyVerbruggen** [comment]
Exactly, that's not what this plugin tries to do.

**Comment by MatthewPringle** [comment]
Do not use https://github.com/sjhoeksma/cordova-plugin-keychain-touch-id as it is not being updated and will fail on both iOS and Android.

The docs are incorrect and I cant see this getting any better in the future.

The plugin has been forked, but at this point it is probably not worth using it.

**Comment by danicholls** [comment]
Please put this in the docs. Sad to find this out after the fact.
