### ISSUE TITLE
verifyFingerprint: EXC_BAD_ACCESS on OSStatus userPresenceStatus

### ISSUE THREAD

**Issue by mjwheatley** [EddyVerbruggen/cordova-plugin-touch-id#25]
App is crashing on `verifyFingerprint` with error message Thread 21: EXC_BAD_ACCESS on the following line:
```
// Start the query and the fingerprint scan and/or device passcode validation
OSStatus userPresenceStatus = SecItemCopyMatching((__bridge CFDictionaryRef)query, NULL);
```

`isAvailable` seems to be working correctly.  I received an error message when no fingerprints were enrolled.  I enrolled a fingerprint and received the success callback, so I called `verifyFingerprint` and the debugger stopped on the line above.

I am using:
Meteor@1.4.3.1
cordova-plugin-touch-id@3.2.0

I have tried removing and reinstalling the plugin to no avail:
meteor remove cordova:cordova-plugin-touch-id
meteor remove-platform ios
meteor add-platform ios
meteor add cordova:cordova-plugin-touch-id@3.2.0

**Comment by mjwheatley** [comment]
I printed out all the arguments for the query
```
NSMutableDictionary * query = [[NSMutableDictionary alloc] initWithObjectsAndKeys:
                                   (__bridge id)(kSecClassGenericPassword), kSecClass,
                                   keychainItemIdentifier, kSecAttrAccount,
                                   keychainItemServiceName, kSecAttrService,
                                   message, kSecUseOperationPrompt,
                                   nil];

```
I saw that `message` was null so I replaced it with @"Debug Message" and it worked.

I checked my code and found a bug in the way I was passing in my message.

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that! I took a look earlier today and couldn't find anything problematic. Glad you found it 👍
