### ISSUE TITLE
Fingerprint or device passcode could not be validated. Status -25293.

### ISSUE THREAD

**Issue by mjwheatley** [EddyVerbruggen/cordova-plugin-touch-id#26]
I accidentally pressed the home button while I was trying to verify my fingerprint and received this error message: 
`Fingerprint or device passcode could not be validated. Status -25293.`

Not sure if this is an issue with the plugin or just a failure of Touch ID.  Just wanted to report the finding.

**Comment by hparth** [comment]
This code is to identify the tigger point when touchId get invalidated. After this point you will have to enter PIN to validate.
It's a usefull but I am not getting this code in iPhone 5s.

**Comment by PratapKancherla** [comment]
I got this issue and it seems to be due to permissions not allowed for the App to use this plugin. I have added "Privacy - Face ID Usage Description" in Info.plist of Xcode and it is working fine post this.
