### ISSUE TITLE
Prevent Passcode

### ISSUE THREAD

**Issue by mabdelwahab** [EddyVerbruggen/cordova-plugin-touch-id#27]
Hello,

I'm using your plugin and it works really great.
But I want to prevent the user from entering his passcode if fingerprint scanning failed.
How can I do this ?

**Comment by EddyVerbruggen** [comment]
From the readme:

> If the onSuccess handler was called, you can scan the fingerprint. There are two options: verifyFingerprint and verifyFingerprintWithCustomPasswordFallback. The first method will offer a fallback option called 'enter passcode' which shows the default passcode UI when pressed. The second method will offer a fallback option called 'enter password' (not passcode) which allows you to provide your own password dialog.

**Comment by mabdelwahab** [comment]
I'm sorry I wasn't clear enough,
I don't want to apply any other option than fingerprint scanning
(No password, passcode, pincode , only fingerprint scanning)

Does the function verifyFingerprintWithCustomPasswordFallback does this ?

**Comment by EddyVerbruggen** [comment]
Yes.

**Comment by mabdelwahab** [comment]
Okay thanks a lot :)

**Comment by harshvardhan12** [comment]
Did u get the solution how to hide enter passcode with this method verifyFingerprintWithCustomPasswordFallback?

**Comment by mabdelwahab** [comment]
@harshvardhan12 yes, use the method "verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel" and set the enter password label to empty string

**Comment by harshvardhan12** [comment]
Thanks @mabdelwahab

**Comment by harshvardhan12** [comment]
Hi @mabdelwahab for iOS ver 9 , if i use "verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel" and set the enter password label to empty string it will come as, the cancel button will align left  and in the right empty String button is there which is clickable. Please help on this regard
Its working for IOS ver 10.

**Comment by mabdelwahab** [comment]
@harshvardhan12 I apologize but I'm a developer like you and I tried all possibilities till it worked with me, so we can ask the creator of the plugin.
@EddyVerbruggen can you help us with the above case ?

**Comment by rmovsoftcorpcom** [comment]
@mabdelwahab , @harshvardhan12 as per your comments I have used verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel to hide passcode button, but now i have a issue, if user has unsuccessful 5 attempts the touchid get disabled/locked for the device, is there a way to unlock without passcode, so that we can implement within the app
