### ISSUE TITLE
TouchID Plaug-in behaves different in different environments

### ISSUE THREAD

**Issue by immigrationanytime** [EddyVerbruggen/cordova-plugin-touch-id#3]
Hi Eddy,

I add TouchID and add support for "Passcode". It works good in development mode.
I release my app on TestFlight and the "Passcode" option changes to "Password".
My code is easy:
    window.plugins.touchid.isAvailable(
        function YesTouchidSupport()
        {
            window.plugins.touchid.verifyFingerprint(
                "TouchID needed for this App",
                authencationSuccessful,
                authenticationFailed
            );
        }, 
    
        function NoTouchidSupport(errorMessage)
        {
            alert("Device does not support TouchID");
        }
    );

I do something wrong?

Thanks,

Hans

**Comment by EddyVerbruggen** [comment]
Sounds like the app has trouble reading something from the keychain, it will then fall back to the other method (password), [see these lines](https://github.com/EddyVerbruggen/cordova-plugin-touchid/blob/master/src/ios/TouchID.m#L51-L55). Perhaps that's normal with TestFlight, I don't know.. can you Google it a bit?

**Comment by immigrationanytime** [comment]
I will. Thanks for speedy reply.

**Comment by immigrationanytime** [comment]
Hello eddy,

I forgot to close before. Sorry.

Hans

**Comment by EddyVerbruggen** [comment]
No worries Hans, thanks!
