### ISSUE TITLE
TouchID, FaceID background mode

### ISSUE THREAD

**Issue by miclaus** [EddyVerbruggen/cordova-plugin-touch-id#30]
is it also possible to perform touch or face verification in the background ?

meaning, i would like to escape any kind of (native) modal, dialog or overlay.

thanks !

**Comment by EddyVerbruggen** [comment]
What do you think Apple would say if you filed a feature request like that? 🤣

**Comment by miclaus** [comment]
@EddyVerbruggen well you tell me, i believe they had FaceID promoted without an overlay, so why shouldn't TouchID have background mode as well ?

anyhow, it wasn't really a feature request, but just a question whether your plugin can do this. i'm of course conscious on some issues concerning a background mode. ;)

**Comment by EddyVerbruggen** [comment]
Haha, well, Apple just doesn't allow that.. otherwise I would gladly add it.

**Comment by miclaus** [comment]
okay, thanks for the info :)
