### ISSUE TITLE
If this plugin suppport FaceID in iPhonex, then what are the methods to test FaceID availability in iPhoneX.

### ISSUE THREAD

**Issue by Fresh-Dev-zunairzakir** [EddyVerbruggen/cordova-plugin-touch-id#31]
Also Please guide me that how we can test it in xcode simulator.

**Comment by EddyVerbruggen** [comment]
There is no current way (in the plugin) that can make you tell whether the user has faceid or touchid on their phone). That's something I'd like to add though.

Regarding testing in the Sim: please Google it.

**Comment by Fresh-Dev-zunairzakir** [comment]
Thanks Eddy but I have tried "window.plugins.touchid.isAvailable()" method and Its is working fine in iPhone6s so If this plugin also work with FaceID in iPhoneX then when this plugin will provide the methods like : window.plugins.touchid.isAvailable()

Or Is there any other way ? I will really appreciate If you guide me in this, Thanks.

**Comment by EddyVerbruggen** [comment]
There's a new callback param added to `isAvailable` -- check out the readme for details 🎉
