### ISSUE TITLE
plugin not working with iPad's with touch id.

### ISSUE THREAD

**Issue by sathishskc77** [EddyVerbruggen/cordova-plugin-touch-id#32]
canEvaluatePolicy returns false on iPad's with registered biometry registered. Tested in iPad pro 10.3 on a ionic 1 project. Works fine in iPhone's.

**Comment by sathishskc77** [comment]
Simulator bug. Changing toggle enrolled state multiple times solved the issue.

**Comment by EddyVerbruggen** [comment]
Thanks for letting us know 👍
