### ISSUE TITLE
iPhoneX FaceID prompt

### ISSUE THREAD

**Issue by kshaaban-** [EddyVerbruggen/cordova-plugin-touch-id#34]
Hi Eddy!

Have a cordova app which includes `v3.2.0` of this plugin.
Upon launching on the new iPhoneX with FaceID, users are prompted with the following:

![touchid_faceid_permission](https://user-images.githubusercontent.com/2960769/32380142-bc4390fe-c085-11e7-96b2-aa1cfbfb5197.png)

Are there any changes required to "update" the app in order to "officially" support FaceID?

**Comment by EddyVerbruggen** [comment]
Hmm interesting - can you perhaps Google that phrase?

**Comment by kshaaban-** [comment]
I tried looking for it, the only mention I could find was in a [iPhoneX review article](https://www.digitaltrends.com/cell-phone-reviews/apple-iphone-x-review/):

> Since Face ID is replacing Touch ID, you may run into some odd issues getting it to work in lieu of a fingerprint sensor.  For example, with our  Discover banking app, it initially asked us to sign in, and the app’s respective settings only made note of activating Touch ID. After enabling it, closing the app, and re-opening it, we got a message indicating the app “was designed to support Touch ID. It has not been updated for Face ID.” It still gave us the option to use Face ID, and we were able to quickly jump into these apps securely with just our face. Most of our apps that required a pin entry or password were able to use Face ID effortlessly, and this is because Apple said Face ID uses the same framework as Touch ID.

**Comment by EddyVerbruggen** [comment]
Ah, so it seems like somehow Apple detects your app hasn't been updated for Face ID, but it still allows you to use it.

It may be as simple as building your app with the iOS 11 SDK (Xcode 9), but I can't tell for sure at this point.

**Comment by kshaaban-** [comment]
For reference, app was built with xcode 9 / iOS 11.0 SDK

I was going through the `LocalAuthentication` documentation and comparing with the implementation in the plugin -- nothing stood out to me. It seems like it should just work as you mentioned in #33! But I'm a not a fluent ObjectiveC speaker 😅

I'll keep an open eye for other reports of such behavior in other apps and keep this issue updated.

Thanks for your insight though.. much appreciated!

**Comment by EddyVerbruggen** [comment]
And thank you as well, I'm sure we can narrow this down one day. I'll be receiving my iPhone X (hopefully) in December and I'm sure that will give me some incentive to dig around.

**Comment by EddyVerbruggen** [comment]
Looks like here's the answer: https://forums.developer.apple.com/thread/91253

If the `NSFaceIDUsageDescription` key (and value) misses in the Plist, then the simulator shows this warning. On a real device (iPhone X) the app probably crashes. So we need to add the string during plugin installation.

**Comment by EddyVerbruggen** [comment]
Check this out 🎉 https://github.com/EddyVerbruggen/cordova-plugin-touch-id#face-id-support

**Comment by kshaaban-** [comment]
🎉 🎉 

Thanks @ajcrites and @EddyVerbruggen
