### ISSUE TITLE
build issue for PhoneGap Build

### ISSUE THREAD

**Issue by nnzfly** [EddyVerbruggen/cordova-plugin-touch-id#36]
I'm using phonegap build to build the app, since yesterday I got this error for ios build:
Error - The following 3rd-party plugin is causing the build to fail and may need to be updated to a newer version: cordova-plugin-touch-id

cordova-plugin-touch-id | npm | 3.3.1

I'm using 
PhoneGap (iOS / Android / Windows)
cli-7.0.1 (4.4.0 / 6.2.3 / 5.0.0)

![image](https://user-images.githubusercontent.com/7309476/32471948-e2cce4ec-c39a-11e7-9202-f1e1ec6593bf.png)
![image](https://user-images.githubusercontent.com/7309476/32471953-ef126e16-c39a-11e7-9e43-ed52e83a0532.png)

**Comment by EddyVerbruggen** [comment]
Can you share the actual log?

Also, please pin your plugins to specific versions so this won't happen. Use a version smaller than 3.3.0 in this case.

**Comment by nnzfly** [comment]
`CompileC /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/Objects-normal/armv7/TouchID.o MyNewApp\ Beta/Plugins/cordova-plugin-touch-id/TouchID.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /project
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Library/Developer/Xcode/DerivedData/ModuleCache -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -miphoneos-version-min=7.0 -g -fvisibility=hidden -Wno-sign-conversion -Wno-infinite-recursion -iquote /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/MyNewApp\ Beta-generated-files.hmap -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/MyNewApp\ Beta-own-target-headers.hmap -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/MyNewApp\ Beta-all-target-headers.hmap -iquote /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/MyNewApp\ Beta-project-headers.hmap -I/project/build/include -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/InstallationBuildProductsLocation/Applications/usr/local/lib/include -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/UninstalledProducts/include -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/include -I/project/build -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/DerivedSources/armv7 -I/Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/DerivedSources -F/project/build -include /private/project/build/sharedpch/MyNewApp\ Beta-Prefix-ergdlxoafgasgydisyfpnnsjwfir/MyNewApp\ Beta-Prefix.pch -MMD -MT dependencies -MF /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/Objects-normal/armv7/TouchID.d --serialize-diagnostics /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/Objects-normal/armv7/TouchID.dia -c /project/MyNewApp\ Beta/Plugins/cordova-plugin-touch-id/TouchID.m -o /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/Objects-normal/armv7/TouchID.o
/project/MyNewApp Beta/Plugins/cordova-plugin-touch-id/TouchID.m:26:11: error: unexpected '@' in program
      if (@available(iOS 11.0, *)) {
          ^
/project/MyNewApp Beta/Plugins/cordova-plugin-touch-id/TouchID.m:27:23: error: property 'biometryType' not found on object of type 'LAContext *'
        if (laContext.biometryType == LABiometryTypeFaceID) {
                      ^
/project/MyNewApp Beta/Plugins/cordova-plugin-touch-id/TouchID.m:27:39: error: use of undeclared identifier 'LABiometryTypeFaceID'
        if (laContext.biometryType == LABiometryTypeFaceID) {
                                      ^
3 errors generated.


The following build commands failed:
	CompileC /Library/Developer/Xcode/DerivedData/MyNewApp_Beta-cegilsfjlfrbngbzlkidbdfjbfjq/Build/Intermediates/ArchiveIntermediates/MyNewApp\ Beta/IntermediateBuildFilesPath/MyNewApp\ Beta.build/Release-iphoneos/MyNewApp\ Beta.build/Objects-normal/armv7/TouchID.o MyNewApp\ Beta/Plugins/cordova-plugin-touch-id/TouchID.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/private/project/cordova/build-release.xcconfig,-workspace,MyNewApp Beta.xcworkspace,-scheme,MyNewApp Beta,-configuration,Release,-destination,generic/platform=iOS,-archivePath,MyNewApp Beta.xcarchive,archive,CONFIGURATION_BUILD_DIR=/private/project/build/device,SHARED_PRECOMPS_DIR=/private/project/build/sharedpch`

**Comment by EddyVerbruggen** [comment]
I guess PhoneGap Build doesn't build with the latest Xcode yet. Just pin the plugin to a previous version for now.
