### ISSUE TITLE
Can't Determine Scanner Existence if No Print Exists

### ISSUE THREAD

**Issue by doverdb** [EddyVerbruggen/cordova-plugin-touch-id#42]
`window.plugins.touchid.isAvailable(...)` calls the error handler if a device has a TouchID/FaceID scanner, but no fingerprints. This is different from the most popular Android plugin for this purpose. It would be very nice to be able to determine if a device has a TouchID/FaceID scanner in order to provide messaging to encourage the user to add a fingerprint/faceprint.

**Comment by EddyVerbruggen** [comment]
I understand, but I don't agree because my rationale was that if `isAvailable` is `true`, you can let your user use bio ID with your app. And it's not up to your app to encourage configuring a system-wide feature.
