### ISSUE TITLE
Plugin not recognizing fingerprint change while app is open

### ISSUE THREAD

**Issue by HeadButcher** [EddyVerbruggen/cordova-plugin-touch-id#45]
Hello everyone.

I'm having an issue with this plugin, which I'm not sure it can be solved.
Here's the thing:

Our corporate App is open, no Fingerprint is configured. 
I can logout and login to the App, and it won't ask me to use Touch ID.
Without closing the app, I browse to Touch ID menu, and add a fingerprint.
Then, getting back to my App, it should ask me if I want to use Touch ID on my next login, but it doesn't.
Is it possible for my app to recognize that a fingerpring has been added without having to close it and open again?
Thanks in advance guys!

**Comment by EddyVerbruggen** [comment]
Perhaps `didFingerprintDatabaseChange` will help you.

**Comment by HeadButcher** [comment]
Hey Eddy, thanks for the tip, but i've already checked on that function.
And even tho it can be useful on my issue, I still have to close my app and open it again when this function returns true in order for the app to show the popup asking for Touch ID.
I'd have to somehow "reload" the plugin from scratch, from inside my app..
Any clue on how to do that?
Thanks a lot!
