### ISSUE TITLE
How can I unlock touchID, if I have error "Biometry is locked out"

### ISSUE THREAD

**Issue by WuglyakBolgoink** [EddyVerbruggen/cordova-plugin-touch-id#48]
Hallo @EddyVerbruggen!

I'm followed @ghost / @mabdelwahab / @harshvardhan12 comments:

--

I have used verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel to hide passcode button, but now i have a issue, if user has unsuccessful 5 attempts the touchid get disabled/locked for the device, is there a way to unlock without passcode, so that we can implement within the app

```json
{
  "localizedDescription": "Biometry is locked out.",
  "code": -8
}
```

```js
Steps
1) window.plugins.touchid.isAvailable
-->onSuccess ↓
2)window.plugins.touchid.didFingerprintDatabaseChange
-->onSucces ↓
3)window.plugins.touchid.verifyFingerprintWithCustomPasswordFallbackAndEnterPasswordLabel
(
    'Bitte legen Sie Ihren Finger auf, um sich anzumelden',
    '',   // <------ hide PIN button
    (msg2) => {
        console.log('msg2', msg2);
    },
    errorCallback
);
```
original comment from https://github.com/EddyVerbruggen/cordova-plugin-touch-id/issues/27

----

possible fix: https://stackoverflow.com/a/45613341

**Comment by EddyVerbruggen** [comment]
Thanks for the suggestion, looks interesting. Anyone up for a PR perhaps?

**Comment by WuglyakBolgoink** [comment]
@EddyVerbruggen 

maybe this can help you :-)
https://github.com/EddyVerbruggen/cordova-plugin-touch-id/pull/87

**Comment by EddyVerbruggen** [comment]
@WuglyakBolgoink That's awesome!

Do you think it would make sense to go one step further and remove the API method and simply call it internally when the iOS code hits the "Biometry is locked out." error? That way it will be seamless for users of this plugin.

**Comment by WuglyakBolgoink** [comment]
@EddyVerbruggen what do you mean here "remove the API method"?

**Comment by WuglyakBolgoink** [comment]
in current app my PM's decided, that we "should not" ask device PIN if bio error happens. And the user should manage this error by himself and not automatically...

but in some cases it will be maybe better to show device-PIN dialog if user did 5x times wrong finger-check.

**Comment by EddyVerbruggen** [comment]
OK, I don't mind. Thanks!
