### ISSUE TITLE
How to check if touch id has been enrolled for ios?

### ISSUE THREAD

**Issue by Abbiee** [EddyVerbruggen/cordova-plugin-touch-id#49]
Is there any way to check if the touch id has been enrolled for ios using ionic like for android?

**Comment by EddyVerbruggen** [comment]
[`isAvailable`](https://github.com/EddyVerbruggen/cordova-plugin-touch-id#usage) should take care of that.

**Comment by Abbiee** [comment]
I mean if i deleted all my fingerprints do **isAvailable** called ?
