### ISSUE TITLE
Fingerprint or device passcode could not be validated. Status -34018.

### ISSUE THREAD

**Issue by Abbiee** [EddyVerbruggen/cordova-plugin-touch-id#50]
Sometimes the popup never comes and shows the following error while deploying it in the device.
Following is the code:
`function iOSFingerPrint() {
          
            window.plugins.touchid.isAvailable(
                                               function() {
                                               var auth = $base64.encode( $scope.user.username + ":" + $scope.user.password);
                                              ss.set(
                                                      function (key) { console.log('Set ' + key); },
                                                      function (error) { console.log('Error ' + error); },
                                                      'token', auth);
                                               isFingerprintsinPhone = true;
                                               iOSFingerPrintPopUp();
                                               }, // success handler: TouchID available
                                               function(msg) {
                                               isFingerprintsinPhone = false;
                                               iOSFingerPrintPopUp();
                                            
                                               if (isFromIosUserValidation == true) {
                                               $scope.deleteFingerPrint();
                                               isFingerprintsinPhone = false;
                                               }
                                               } // error handler: no TouchID available
                                               );
           
            }
            
            function iOSFingerPrintPopUp() {
            
            if (isFingerprintsinPhone == false) {
            $scope.deleteFingerPrint();
            } else if (isFingerprintsinPhone == true) {
           // alert('It is here');
            window.plugins.touchid.verifyFingerprint(
                                                     'Scan your fingerprint please', // this will be shown in the native scanner popup
                                                     function(msg) {
                                                     $scope.disableFingerPrint=false;
                                                     localStorage.setItem('hasEnrolledFingerprints',true);
                                                     localStorage.setItem('isFingerPrintRequired',true);
                                                     localStorage.setItem('notNullFlag',true);
                                                     $scope.myPopup6.close();
                                                     if (isFromIosUserValidation == true) {
                                                     $scope.showCartStatuspopUp();
                                                     }
                                                     }, // success handler: fingerprint accepted
                                                     function(msg) {
                                    
                                                     } // error handler with errorcode and localised reason
                                                     );
            }
            
            }`

**Comment by Abbiee** [comment]
very poor responsibility shown out and bad maintenance of plugin.

**Comment by EddyVerbruggen** [comment]
What do you mean?

**Comment by Abbiee** [comment]
@EddyVerbruggen I mean a precise readme for the status codes have been much better for better understnading :)

**Comment by EddyVerbruggen** [comment]
So you're not happy with the readme and you choose to communicate that by saying "very poor responsibility shown out and bad maintenance of plugin."?

I'm not sure that's the best way to report an issue to a project that someone tries to maintain in his spare time. Also, you may want to read up on what an MIT license means.

**Comment by Abbiee** [comment]
@EddyVerbruggen sorry to say like that... But my friend even if you build a brick in your spare time it should be worth it to balance a block of brick on it. Anyways thanks for the replies friend 👍 )
