### ISSUE TITLE
Request for help on retry count change

### ISSUE THREAD

**Issue by ejonnadula** [EddyVerbruggen/cordova-plugin-touch-id#62]
I am using "cordova-plugin-touch-id" plugin to implement touch id 
functionality in my application. When I try with wrong finger print 
scanning after 3rd attempt plugin is responding like "Application 
retry limit exceeded". Is there a way to get call back response each 
time instead of waiting for 3rd failure attempt?.  Where is the number 
of retries (3 and 5) are configured in plugin?. Is there a way to 
change these values to 1? In my application when the user tries with 
wrong finger I need to insert a DB record with failure attempt status 
after 5 failures i need to lock the user login. Please help me.
Thanks,
Eswar

**Comment by EddyVerbruggen** [comment]
Look up Apples docs on this please, it's not something the plugin dictates nor can change.
