### ISSUE TITLE
How to customise TouchID popup

### ISSUE THREAD

**Issue by cvinodhkumar77** [EddyVerbruggen/cordova-plugin-touch-id#65]
I want to customise the popup of TouchID.  There is a text as "Touch ID for 'ios'" in the TouchID alert.  I want to change this text and how to disable PIN authentication that we get when we are exceeding the limit of 3.  Please suggest

**Comment by EddyVerbruggen** [comment]
Please search the iOS docs on how to do those things and report back here. Thanks!
