### ISSUE TITLE
verifyFingerprint callbacks not called iOS 9.2

### ISSUE THREAD

**Issue by RevillWeb** [EddyVerbruggen/cordova-plugin-touch-id#7]
Hi,

I've attempted to integrate your plugin but I am having some issues. When I call verifyFingerprint and attempt to use my finger to authenticate neither of the success or error callbacks get called.

If I choose the enter passcode option, this does work however. I think this might be due to an iOS API change because the same issue occurs with two other plugins I have tried (But yours is better suited for my needs).

Would be great if we could find out what has changed and patch it - thanks for your awesome work on the plugin.

**Comment by RevillWeb** [comment]
It appears that the callbacks do work however only the second time the function is called. For example I would need to call isAvailable() twice to get a result. Any thoughts on this would be greatly appreciated.

**Comment by EddyVerbruggen** [comment]
Please share your project with me as I can't reproduce this on a vanilla Cordova CLI project and this is the first time I heard about this.

**Comment by RevillWeb** [comment]
Hi Eddy, Thanks for your reply. Unfortunately I am unable to share the project, but if your saying that it all works fine for you with a vanilla Cordova project then it must be something my end. I've now tried four Touch ID plugins all with the same results while all the other plugins I am using working perfectly fine - its very strange. Could I ask what Cordova CLI version you are using? Thanks again.

**Comment by EddyVerbruggen** [comment]
CLI 5.4.1.

I just created [a new project (dropbox link)](https://dl.dropboxusercontent.com/u/10061342/touchidtest2.zip) to support my claim and it still works fine for me (iOS 9.2, iPhone 6s).

Please download the app, open the file `platforms/ios/HelloCordova.xcodeproj` and deploy it to your device.

**Comment by RevillWeb** [comment]
Hi @EddyVerbruggen thank you very much for providing this. I've managed to get it all working not sure what was going on but if I tried this plugin via the console (via Safari) and used console.logs in the callbacks no data was being output, leaving me to wrongly believe it wasn't working. Thanks again for your time.
