### ISSUE TITLE
"Class not found" when calling isAvailable

### ISSUE THREAD

**Issue by adamdport** [EddyVerbruggen/cordova-plugin-touch-id#71]
Trying this plugin for the first time. When I call `isAvailable` in my emulator, my error function (second callback function) runs and is passed the message "Class not found". My emulator DOES have touchID available and was working with another plugin. I AM waiting for `deviceready` so it's not that.

Any ideas?

**Comment by danicholls** [comment]
Is this on Android? I'm having the same result in #72

**Comment by adamdport** [comment]
Yes, Android.

**Comment by danicholls** [comment]
FYI, as I just realized over in the other issue, Android isn't covered by this plugin. See https://github.com/mjwheatley/cordova-plugin-android-fingerprint-auth for an Android auth plugin.

**Comment by adamdport** [comment]
Wow. How embarassing. Totally didn't notice that. Thanks!
