### ISSUE TITLE
Version in plugin.xml has outdated version.

### ISSUE THREAD

**Issue by torrolt** [EddyVerbruggen/cordova-plugin-touch-id#73]
Version in plugin.xml is described as "3.3.1"
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin xmlns="http://apache.org/cordova/ns/plugins/1.0"
        id="cordova-plugin-touch-id"
        version="3.3.1">
```

Should be 3.4.0

**Comment by torrolt** [comment]
I didn't notice anything breaking, it just creates some confusion when checked for plugin version in ios.json after adding ios platform, as the old version is displayed there.

**Comment by EddyVerbruggen** [comment]
Fair enough. Changed it to 3.4.0.
