### ISSUE TITLE
iOS: Passcode instead of Biometric authentication

### ISSUE THREAD

**Issue by idoodler** [EddyVerbruggen/cordova-plugin-touch-id#78]
I am experiencing issues with the biometric authentication on iOS 12.2 on my iPhone X.

I am calling `verifyFingerprint` but the iOS passcode dialog pops up instead of the Face ID dialog.

In the Console Application I can see a strange error:
<img src="https://idoodler.de/files/touchID.png"/>

Anyone experiencing similar issues?

**Comment by idoodler** [comment]
I just resolved the issue by adding the key `NSFaceIDUsageDescription` to the Info.plist. It looks like it is a mandatory key...

**Comment by EddyVerbruggen** [comment]
That's correct, but based on this, Cordova should add that automatically for you:

https://github.com/EddyVerbruggen/cordova-plugin-touch-id/blob/6c398e79364b666d7131b91d82932c4fb9349373/plugin.xml#L39-L43
