### ISSUE TITLE
TouchID dialog is not displayed when updating to iOS 13.1.

### ISSUE THREAD

**Issue by toyohikomotoyama** [EddyVerbruggen/cordova-plugin-touch-id#84]
TouchID dialog is not displayed when updating to iOS 13.1.
FaceID works without problems.
When you place your finger on the button at the time of TouchID authentication, a dialog is displayed and you can authenticate.

There is also a report that an error has occurred at secItemCopyMatching.
https://forums.developer.apple.com/thread/122628

**Comment by toyohikomotoyama** [comment]
> TouchID dialog is not displayed when updating to iOS 13.1.
> FaceID works without problems.
> When you place your finger on the button at the time of TouchID authentication, a dialog is displayed and you can authenticate.

**Comment by localdrive** [comment]
same here

**Comment by shrivallabhDeshmukh** [comment]
same here .Its taking time to load touch ID dialog and sometime it doesn't even load.

**Comment by pablorussi** [comment]
Same here. Any workaround for this?

**Comment by toyohikomotoyama** [comment]
Solved by updating to iOS13.1.3!
