### ISSUE TITLE
iPhoneX FaceID prompt permission

### ISSUE THREAD

**Issue by WuglyakBolgoink** [EddyVerbruggen/cordova-plugin-touch-id#92]
if user click on "Don't allow", then there is no possibility to reactivate this option anymore. 

![image](https://user-images.githubusercontent.com/2271337/75227899-5aa6de00-57af-11ea-8e49-5f147d452bfb.png)

In this case user should open phone settings and reactivate permissions manually:

![image](https://user-images.githubusercontent.com/2271337/75228578-97bfa000-57b0-11ea-8a0f-7158699f0ea2.png)

Is it possible to add some new "feature"-function for reactivating this permission?

**Comment by EddyVerbruggen** [comment]
Nope, that's just how iOS works.
